[tool.poetry]
name = "favoritescloudbot"
version = "0.1.0"
description = ""
authors = ["zaymovskey <zaymovskey@mail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "^2.25.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
