"""remove username"

Revision ID: 112fbeed8726
Revises: c87a3e6c1faa
Create Date: 2023-02-28 14:06:43.773054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112fbeed8726'
down_revision = 'c87a3e6c1faa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
