"""user current folder id

Revision ID: 16f203dd3c4c
Revises: b9ec598ac65f
Create Date: 2023-02-26 20:17:10.016565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f203dd3c4c'
down_revision = 'b9ec598ac65f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_folder_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_folder_id')
    # ### end Alembic commands ###
