"""remove current_menu

Revision ID: 32f9c43338a0
Revises: 112fbeed8726
Create Date: 2023-02-28 14:52:59.029758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32f9c43338a0'
down_revision = '112fbeed8726'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_menu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_menu', postgresql.ENUM('add_folder', name='menu_enum'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
