"""add username"

Revision ID: 922abdaaa963
Revises: 16f203dd3c4c
Create Date: 2023-02-28 13:49:26.892643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922abdaaa963'
down_revision = '16f203dd3c4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
