"""remove current folder id

Revision ID: c87a3e6c1faa
Revises: 922abdaaa963
Create Date: 2023-02-28 13:53:27.244047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87a3e6c1faa'
down_revision = '922abdaaa963'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_folder_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_folder_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
